FROM golang:1.20.7 AS build-stage

WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /hello-web-app

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /hello-web-app /hello-web-app

EXPOSE 8080

USER nonroot:nonroot

CMD ["/hello-web-app"]

